spring:
  application:
    name:   catalog

  datasource:
    url:    jdbc:h2:mem:catalog
    driver-class-name:  org.h2.Driver
    username:   sa
    password:   password

  h2:
    console:
      enabled:  true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      format_sql: true

  sql:
    init:
      mode: always

logging:
  level:
    '[com.samnart.catalog]': DEBUG
    '[org.hibernate.sql]': DEBUG
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE

server:
  port: 8080
