server:
  port: 8082

eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

spring:
  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:                        
        format_sql: true
  
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    health:
      show-details: always

app:
  version: 1.0
  environment: development

logging:
  level:
    com.samnart.order-service: DEBUG